### ISSUE TITLE
Microposts original data not matching with what gerbil expects

### ISSUE THREAD

**Issue by sagnik** [dice-group/gerbil#206]
Please refer to #41 , The [wiki](https://github.com/dice-group/gerbil/wiki/Licences-for-datasets) mentions that it expects the data in certain formats, specifically: 

### Microposts2013
```
gerbil_data/datasets/microposts2013/goldStandard.tsv
gerbil_data/datasets/microposts2013/testSet.tsv
gerbil_data/datasets/microposts2013/TweetsTrainingSetCH.tsv
```

### Microposts2014
```
gerbil_data/datasets/microposts2014/Microposts2014-NEEL_challenge_TweetsTestSet.csv
gerbil_data/datasets/microposts2014/Microposts2014-NEEL_challenge_TweetsTrainingSet.csv
```

### Microposts2015

```
gerbil_data/datasets/microposts2015/dev/NEEL2015-dev-gold_v3.tsv
gerbil_data/datasets/microposts2015/dev/NEEL2015-dev-tweets.tsv
gerbil_data/datasets/microposts2015/test/NEEL2015-test-gold_v2.tsv
gerbil_data/datasets/microposts2015/test/NEEL2015-test-tweets.tsv
gerbil_data/datasets/microposts2015/training/NEEL2015-training-gold_v4.tsv
gerbil_data/datasets/microposts2015/training/NEEL2015-training-tweets_v2.tsv
```

### Microposts2016

```
gerbil_data/datasets/microposts2016/Dev Set/NEEL2016-dev.tsv
gerbil_data/datasets/microposts2016/Dev Set/NEEL2016-dev_neel.gs
gerbil_data/datasets/microposts2016/Test Set/NEEL2016-test.tsv
gerbil_data/datasets/microposts2016/Test Set/NEEL2016-test_neel.gs
gerbil_data/datasets/microposts2016/Training Set/NEEL2016-training.tsv
gerbil_data/datasets/microposts2016/Training Set/NEEL2016-training_neel.gs
```

I downloaded microposts data from the following sources:

- **2013** :  http://oak.dcs.shef.ac.uk/msm2013/ie_challenge/MSM2013-CEChallengeFinal.zip ([source](http://oak.dcs.shef.ac.uk/msm2013/))
- **2014** :  http://ceur-ws.org/Vol-1141/microposts2014-neel_challenge_gs.zip ([source](http://ceur-ws.org/Vol-1141/))
- **2015** :  http://ceur-ws.org/Vol-1141/microposts2015-neel_challenge_gs.zip ([source](http://ceur-ws.org/Vol-1395/))
- **2016** :  http://ceur-ws.org/Vol-1141/microposts2016-neel_challenge_gs.zip ([source](http://ceur-ws.org/Vol-1691/))

For 2013, the contents of the zip file do match, for others, the contents are as follows:

#### 2014

```
Microposts2014-NEEL_Dataset-Test.GS
Microposts2014-NEEL_challenge_README  
Microposts2014-NEEL_Dataset-Train.GS
```

#### 2015

```
AUTHOR.txt1
microposts2015-neel_challenge_gs_cc-by4.0_license.txt
NEEL2015-dev-gold.tsv
NEEL2015-dev-tweets-ids.tsv
NEEL2015-README
NEEL2015-test-gold.tsv
NEEL2015-test-tweets-ids.tsv
NEEL2015-training-gold.tsv
NEEL2015-training-tweets-ids.tsv
```

### 2016

```
microposts2016-neel-dev_neel.gs
microposts2016-neel-dev-tweets-ids.tsv
microposts2016-neel-README
microposts2016-neel-test_neel.gs
microposts2016-neel-test-tweets-ids.tsv
microposts2016-neel-training_neel.gs
microposts2016-neel-training-tweets-ids.tsv
```

This is clearly different from what Gerbil expects. If you have any suggestions, please let me know.  Also, as @TortugaAttack suggested in #41, I went through the logs in my local machine and it does seem that the microposts data is **not** loaded:

```
sagnik@research:~/gerbil$ cat gerbil.log | grep -i micropost 
2017-08-02 01:03:28,793 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2014-Train" failed. It won't be available.>
2017-08-02 01:03:28,794 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2013-Test" failed. It won't be available.>
2017-08-02 01:03:28,794 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2013-Train" failed. It won't be available.>
2017-08-02 01:03:28,796 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2016-Train" failed. It won't be available.>
2017-08-02 01:03:28,798 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2015-Train" failed. It won't be available.>
2017-08-02 01:03:28,799 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2016-Dev" failed. It won't be available.>
2017-08-02 01:03:28,799 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2016-Test" failed. It won't be available.>
2017-08-02 01:03:28,799 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2015-Dev" failed. It won't be available.>
2017-08-02 01:03:28,800 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2015-Test" failed. It won't be available.>
2017-08-02 01:03:28,800 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2014-Test" failed. It won't be available.>
2017-08-02 02:34:10,926 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2014-Train" failed. It won't be available.>
2017-08-02 02:34:10,926 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2013-Test" failed. It won't be available.>
2017-08-02 02:34:10,927 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2013-Train" failed. It won't be available.>
2017-08-02 02:34:10,928 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2016-Train" failed. It won't be available.>
2017-08-02 02:34:10,929 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2015-Train" failed. It won't be available.>
2017-08-02 02:34:10,930 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2016-Dev" failed. It won't be available.>
2017-08-02 02:34:10,930 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2016-Test" failed. It won't be available.>
2017-08-02 02:34:10,930 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2015-Dev" failed. It won't be available.>
2017-08-02 02:34:10,930 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2015-Test" failed. It won't be available.>
2017-08-02 02:34:10,931 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Microposts2014-Test" failed. It won't be available.>

```

**Comment by TortugaAttack** [comment]
Thanks for creating a new issue! :) 

hmm it looks allright. The datasets you linked are correct and should work with the implemented Wrapper. 
The logs suggest that the properties cant find the Microposts files. 
I will look closer into it tomorrow or todays evening!

**Comment by MichaelRoeder** [comment]
I assume that you simply have to rename the files and move them in the directory where they are expected. Can you please try this?

The "check" that is done by GERBIL when starting the server is very simple and does only look for the files that it is expecting. If there would be a problem with the data inside the files, you would encounter it when you try to benchmark something with these datasets.

**Comment by TortugaAttack** [comment]
i used the Microposts 2014 set you provided, added them to the gerbil_data and changed the file name. It worked. 

So i guess what MichaelRoeder just said seems correct.

**Comment by sagnik** [comment]
Ok, I'll test all of them and keep you posted. 

Sagnik

**Comment by sagnik** [comment]
Did you make the change in the code or renamed the files? This is what I have done:

```
2014
----
mv Microposts2014-NEEL_Dataset-Test.GS Microposts2014-NEEL_challenge_TweetsTestSet.csv
mv Microposts2014-NEEL_Dataset-Train.GS Microposts2014-NEEL_challenge_TweetsTrainingSet.csv

2015
-------
mv NEEL2015-dev-gold.tsv dev/NEEL2015-dev-gold_v3.tsv
mv NEEL2015-dev-tweets-ids.tsv dev/NEEL2015-dev-tweets.tsv
mv NEEL2015-test-gold.tsv test/NEEL2015-test-gold_v2.tsv
mv NEEL2015-test-tweets-ids.tsv test/NEEL2015-test-tweets.tsv
mv NEEL2015-training-gold.tsv training/NEEL2015-training-gold_v4.tsv
mv NEEL2015-training-tweets-ids.tsv training/NEEL2015-training-tweets_v2.tsv


2016
------

mv microposts2016-neel-dev_neel.gs Dev\ Set/NEEL2016-dev_neel.gs
mv microposts2016-neel-dev-tweets-ids.tsv Dev\ Set/NEEL2016-dev.tsv
mv microposts2016-neel-test_neel.gs Test\ Set/NEEL2016-test_neel.gs
mv microposts2016-neel-test-tweets-ids.tsv Test\ Set/NEEL2016-test.tsv 
mv microposts2016-neel-training_neel.gs Training\ Set/NEEL2016-training_neel.gs
mv microposts2016-neel-training-tweets-ids.tsv Training\ Set/NEEL2016-training.tsv

```
This is the output I get

 Annotator          | Dataset               | Micro F1                                                  |
------------------- |---------------------- |-----------------------------------------------------------|
 AIDA               | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 AIDA               | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 AIDA               | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 AIDA               | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 AIDA               | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 AIDA               | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 AIDA               | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 AIDA               | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 Babelfy            | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 Babelfy            | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 Babelfy            | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 Babelfy            | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 Babelfy            | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 Babelfy            | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 Babelfy            | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 Babelfy            | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 DBpedia Spotlight  | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 DBpedia Spotlight  | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 DBpedia Spotlight  | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 DBpedia Spotlight  | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 DBpedia Spotlight  | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 DBpedia Spotlight  | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 DBpedia Spotlight  | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 DBpedia Spotlight  | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 Dexter             | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 Dexter             | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 Dexter             | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 Dexter             | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 Dexter             | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 Dexter             | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 Dexter             | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 Dexter             | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 FOX                | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 FOX                | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 FOX                | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 FOX                | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 FOX                | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 FOX                | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 FOX                | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 FOX                | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 FRED               | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 FRED               | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 FRED               | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 FRED               | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 FRED               | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 FRED               | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 FRED               | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 FRED               | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 FREME NER          | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 FREME NER          | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 FREME NER          | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 FREME NER          | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 FREME NER          | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 FREME NER          | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 FREME NER          | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 FREME NER          | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 WAT                | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 WAT                | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 WAT                | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 WAT                | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 WAT                | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 WAT                | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 WAT                | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 WAT                | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 xLisa-NER          | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 xLisa-NER          | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 xLisa-NER          | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 xLisa-NER          | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 xLisa-NER          | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 xLisa-NER          | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 xLisa-NER          | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 xLisa-NER          | Microposts2016-Train  | Got an unexpected exception while running the experiment. |
 xLisa-NGRAM        | Microposts2014-Test   | The dataset couldn't be loaded.                           |
 xLisa-NGRAM        | Microposts2014-Train  | The dataset couldn't be loaded.                           |
 xLisa-NGRAM        | Microposts2015-Dev    | Got an unexpected exception while running the experiment. |
 xLisa-NGRAM        | Microposts2015-Test   | Got an unexpected exception while running the experiment. |
 xLisa-NGRAM        | Microposts2015-Train  | Got an unexpected exception while running the experiment. |
 xLisa-NGRAM        | Microposts2016-Dev    | Got an unexpected exception while running the experiment. |
 xLisa-NGRAM        | Microposts2016-Test   | Got an unexpected exception while running the experiment. |
 xLisa-NGRAM        | Microposts2016-Train  | Got an unexpected exception while running the experiment. |

**Comment by TortugaAttack** [comment]
`cp Microposts2014-NEEL_Dataset-Test.GS gerbil_data/datasets/microposts2014/Microposts2014-NEEL_challenge_TweetsTestSet.csv`

**Comment by TortugaAttack** [comment]
and they are not hardcoded but in the `dataset.properties` file in `src/main/properties` ;)

**Comment by sagnik** [comment]
I exactly followed your instruction, this is what I am getting from the log:

```
GerbilException: GerbilException: Dataset is malformed. Each line shoud have an even number of cells. Malformed line = [92619158411411456] (error type -104: The dataset couldn't be loaded.) (error type -104: The dataset couldn't be loaded.)
        at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getDataset(AbstractDatasetConfiguration.java:52)
        at org.aksw.gerbil.execute.ExperimentTask.run(ExperimentTask.java:102)
        at org.aksw.simba.topicmodeling.concurrent.workers.WorkerImpl.run(WorkerImpl.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by TortugaAttack** [comment]
hmm, the dataset has empty lines (only IDs) 
The wrapper was probably written with a cleaned up dataset. 

I will handle it in the code. But not sure right now whats the best way. 
Thus i will take care of it tomorrow. 
For now simply remove all those empty lines. ;)

This seems to be the problem for all the datasets.

**Comment by sagnik** [comment]
Yup. It fails with empty id lines. Can confirm. But more importantly, for 2014, the filetype is `TSV`, not `CSV`. If an id has multiple named entities, each gets separated by a tab.

**Comment by TortugaAttack** [comment]
This python script should do the line removal trick (tested only with MP2014)
```
import re
import sys

fileInput = sys.argv[1]
fileOutput = sys.argv[2]

f = open(fileInput)
out = open(fileOutput, 'w')

for line in f:
	if not re.match('[0-9]+$', line):
		out.write(line)

out.close()
f.close()
```

`python removeLines.py Microposts2014-NEEL_Dataset-Test.GS Microposts2014-NEEL_challenge_TweetsTestSet.csv`

**Comment by sagnik** [comment]
you have been very helpful @TortugaAttack ! I am assuming you are converting micropost data to NFI format? If you could point out the code for me, I could give it a try. Thanks anyway.

**Comment by TortugaAttack** [comment]
ah thanks! 
but i just did it :D 
2014 should work now 
Not sure about 2015 and 2016, cannot download them, can you provide the logs for them if they still not work?

**Comment by sagnik** [comment]
ok, ll test and keep you updated.

**Comment by sagnik** [comment]
Extremely sorry for the late reply, but this is the result I get, which I don't think is correct:

| Annotator | Dataset             |                    | Micro F1 | Micro Precision | Micro Recall | Macro F1 | Macro Precision | Macro Recall | Error Count | avg millis/doc | confidence threshold | Timestamp           | GERBIL version |   |
|-----------|---------------------|--------------------|----------|-----------------|--------------|----------|-----------------|--------------|-------------|----------------|----------------------|---------------------|----------------|---|
| AIDA      | Microposts2014-Test |                    | 1        | 1               | 1            | 1        | 1               | 1            | 0           | 895            | 0                    | 2017-08-06 19:49:38 | 1.2.5          |   |
| AIDA      | Microposts2014-Test | Entity Recognition | 1        | 1               | 1            | 1        | 1               | 1            | 0           |                |                      | 2017-08-06 19:49:38 | 1.2.5          |   |
| AIDA      | Microposts2014-Test | D2KB               | 1        | 1               | 1            | 1        | 1               | 1            | 0           |                |                      | 2017-08-06 19:49:38 | 1.2.5          |

**Comment by TortugaAttack** [comment]
Nope, that is not correct :D 
http://gerbil.aksw.org/gerbil/experiment?id=201708070004 
The global version works. 
Hence i am thinking it is a diff between the dataset we use global and the dataset you use. 
I will check into that.

**Comment by TortugaAttack** [comment]
Sorry it took so long!
I finally could check the datasets against each other. 
The ones you uses are quite different than the ones we got.

Yours missing the tweet itself and thus cannot be used with the MP2014 Wrapper. 
This will results into the 1 with AIDA

Sorry this took so long!

**Comment by MichaelRoeder** [comment]
@sagnik If the last post answered your question, please close this issue. Thanks.
