### ISSUE TITLE
Experiments not running locally 

### ISSUE THREAD

**Issue by pepe3059** [dice-group/gerbil#246]
Hi, 

I'm trying to run Gerbil (1.2.6) but it is not working in a local environment. When I want to see the progress of the experiment, I got the following error:

`GRAVE: Servlet.service() for servlet [dispatcher] in context with path [/gerbil] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: com/hp/hpl/jena/rdf/model/impl/IO_Ctl] with root cause
java.lang.ClassNotFoundException: com.hp.hpl.jena.rdf.model.impl.IO_Ctl
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	at com.github.jsonldjava.jena.JenaJSONLD.init(JenaJSONLD.java:135)
	at com.github.jsonldjava.jena.JenaJSONLD.<clinit>(JenaJSONLD.java:121)
	at org.aksw.gerbil.dataid.DataIDGenerator.createDataIDModel(DataIDGenerator.java:86)
	at org.aksw.gerbil.web.MainController.experiment(MainController.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)`

Likewise if the page is refreshed, the error changes to:
`org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.github.jsonldjava.jena.JenaJSONLD
	org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1275)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:951)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)`

Does Jena 3.1 supports such missing class? 
Moreover, Gerbil 1.2.5  does not send requests in a web service annotator experiment (although the testing communication works fine).

Hope yo can help me

Thanks,
José

**Comment by TortugaAttack** [comment]
`com/hp/hpl/jena/rdf/model/impl/IO_Ctl` is from Jena 2.X not 3.X. 
The JSON-LD library which we use is based upon  2.X. I'll try to figure a way out.

**Comment by TortugaAttack** [comment]
Okay, the 2.x needed the dependency to create JSON-LD, which if i understood correctly is now implemented in 3.x itself. 
I'll check this somewhen today and let you know and push the changes if it works :)

**Comment by TortugaAttack** [comment]
done, should be working (works for me) 
please check again, and if it worked close the issue :)

**Comment by pepe3059** [comment]
Hey thank you, I tested this last version and seems to work fine. However, it takes a while before the first execution starts. Tested on MacOS 10.10.5 and Ubuntu 16.04

Thank you
