### ISSUE TITLE
Multiple cache errors

### ISSUE THREAD

**Issue by alexanderpanchenko** [dice-group/gerbil#269]
Hello, 

I observed the following behaviour of GERBIL.  **Could you please write if this is normal and if this can affect the evaluation scores in any way?**

Here are the steps which I follow:

1. Start GERBIL using ./start.sh (on Mac OS X, Oracle Java 1.8+) as a web service

2. Add a custom NIF web service and setup a D2KB experiment. 

3. The experiment does not start right away (waiting of several minutes is needed). After the start the system seems to work (and produce the evaluation scores), however, inumerous warning about the cache errors of the sort presented below are printed by GERBIL:

```
2018-07-19 19:50:07,272 [pool-5-thread-3] ERROR [org.aksw.gerbil.dataset.check.impl.FileBasedCachingEntityCheckerManager] - <Exception while writing cache to file. Aborting.>
java.io.FileNotFoundException: /Users/panchenko/work/gerbil/gerbil_data/cache/entityCheck.cache_temp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.aksw.gerbil.dataset.check.impl.FileBasedCachingEntityCheckerManager.performCacheStorage(FileBasedCachingEntityCheckerManager.java:213)
	at org.aksw.gerbil.dataset.check.impl.FileBasedCachingEntityCheckerManager.checkUri(FileBasedCachingEntityCheckerManager.java:168)
	at org.aksw.gerbil.dataset.check.impl.EntityCheckerManagerImpl.checkMeaning(EntityCheckerManagerImpl.java:84)
	at org.aksw.gerbil.dataset.check.impl.EntityCheckerManagerImpl.checkMarkings(EntityCheckerManagerImpl.java:64)
	at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getPreparedDataset(AbstractDatasetConfiguration.java:79)
	at org.aksw.gerbil.dataset.SingletonDatasetConfigImpl.getPreparedDataset(SingletonDatasetConfigImpl.java:50)
	at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getDataset(AbstractDatasetConfiguration.java:50)
	at org.aksw.gerbil.execute.ExperimentTask.run(ExperimentTask.java:102)
	at org.aksw.simba.topicmodeling.concurrent.workers.WorkerImpl.run(WorkerImpl.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MichaelRoeder** [comment]
GERBIL uses an in-memory cache for entities that have been checked and sameAs relation information. This cache will typically persisted from time to time. However, this is failing when the file mentioned in the exception can not be written. I assume that the directory does not exist. So if you create it manually, the error should be gone.

The error won't influence your results. It may increase the time GERBIL needs for handling the uploaded datasets because it will loose all the information in the cache when you restart it.
