### ISSUE TITLE
How to terminate the experiment

### ISSUE THREAD

**Issue by BeerTai** [dice-group/gerbil#373]
How can I terminate the following state.
```
Experiments could take a while
There are 32 other tasks pending before your latest task on 12 Worker(s).

```

**Comment by MichaelRoeder** [comment]
I assume that you execute GERBIL locally. In that case, you can simply restart the GERBIL web service. However, please note that this will stop all submitted experiments.

**Comment by BeerTai** [comment]
Sorry, I am not very familiar with gerbil, I don’t know how to restart the web service. All gerbil services have been closed.
<img width="1432" alt="Screen Shot 2020-12-01 at 10 30 04 AM" src="https://user-images.githubusercontent.com/29746659/100689831-37edc980-33c0-11eb-87f4-a3aed3cab5c9.png">

**Comment by BeerTai** [comment]
I deployed GERBIL successfully on my mac. when i tried to configure an experiment on page http://localhost:1234/gerbil/config and run it, the log shows some ERROR and the experiment result tell me it is running.
some ERRORs are showed below:
```
2020-12-02 10:32:38,780 [pool-1-thread-4] ERROR [org.aksw.gerbil.http.AbstractHttpRequestEmitter] - <Exception while sending request.>
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.aksw.gerbil.http.AbstractHttpRequestEmitter.sendRequest(AbstractHttpRequestEmitter.java:151)
	at org.aksw.gerbil.http.AbstractHttpRequestEmitter.sendRequest(AbstractHttpRequestEmitter.java:145)
	at org.aksw.gerbil.semantic.sameas.impl.wiki.WikipediaApiBasedSingleUriSameAsRetriever.queryRedirect(WikipediaApiBasedSingleUriSameAsRetriever.java:102)
	at org.aksw.gerbil.semantic.sameas.impl.wiki.WikipediaApiBasedSingleUriSameAsRetriever.retrieveSameURIs(WikipediaApiBasedSingleUriSameAsRetriever.java:66)
	at org.aksw.gerbil.semantic.sameas.impl.DomainBasedSameAsRetrieverManager.retrieveSameURIs(DomainBasedSameAsRetrieverManager.java:70)
	at org.aksw.gerbil.semantic.sameas.impl.DomainBasedSameAsRetrieverManager.retrieveSameURIs(DomainBasedSameAsRetrieverManager.java:58)
	at org.aksw.gerbil.semantic.sameas.impl.UriFilteringSameAsRetrieverDecorator.retrieveSameURIs(UriFilteringSameAsRetrieverDecorator.java:56)
	at org.aksw.gerbil.semantic.sameas.impl.CrawlingSameAsRetrieverDecorator.addSameURIs(CrawlingSameAsRetrieverDecorator.java:73)
	at org.aksw.gerbil.semantic.sameas.impl.CrawlingSameAsRetrieverDecorator.retrieveSameURIs(CrawlingSameAsRetrieverDecorator.java:52)
	at org.aksw.gerbil.semantic.sameas.impl.cache.FileBasedCachingSameAsRetriever.requestUri(FileBasedCachingSameAsRetriever.java:147)
	at org.aksw.gerbil.semantic.sameas.impl.cache.FileBasedCachingSameAsRetriever.retrieveSameURIs(FileBasedCachingSameAsRetriever.java:135)
	at org.aksw.gerbil.semantic.sameas.impl.AbstractSameAsRetrieverDecorator.addSameURIs(AbstractSameAsRetrieverDecorator.java:43)
	at org.aksw.gerbil.semantic.sameas.SameAsRetrieverUtils.addSameURIsToMarkings(SameAsRetrieverUtils.java:31)
	at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getPreparedDataset(AbstractDatasetConfiguration.java:75)
	at org.aksw.gerbil.dataset.SingletonDatasetConfigImpl.getPreparedDataset(SingletonDatasetConfigImpl.java:50)
	at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getDataset(AbstractDatasetConfiguration.java:50)
	at org.aksw.gerbil.execute.ExperimentTask.run(ExperimentTask.java:104)
	at org.aksw.simba.topicmodeling.concurrent.workers.WorkerImpl.run(WorkerImpl.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-12-02 10:32:38,782 [pool-1-thread-4] ERROR [org.aksw.gerbil.semantic.sameas.impl.wiki.WikipediaApiBasedSingleUriSameAsRetriever] - <Got an exception while querying the wiki api of "en.wikipedia.org". Returning null.>
GerbilException: Exception while sending request. (error type -106: Got an unexpected exception while running the experiment.)
	at org.aksw.gerbil.http.AbstractHttpRequestEmitter.sendRequest(AbstractHttpRequestEmitter.java:172)
	at org.aksw.gerbil.http.AbstractHttpRequestEmitter.sendRequest(AbstractHttpRequestEmitter.java:145)
	at org.aksw.gerbil.semantic.sameas.impl.wiki.WikipediaApiBasedSingleUriSameAsRetriever.queryRedirect(WikipediaApiBasedSingleUriSameAsRetriever.java:102)
	at org.aksw.gerbil.semantic.sameas.impl.wiki.WikipediaApiBasedSingleUriSameAsRetriever.retrieveSameURIs(WikipediaApiBasedSingleUriSameAsRetriever.java:66)
	at org.aksw.gerbil.semantic.sameas.impl.DomainBasedSameAsRetrieverManager.retrieveSameURIs(DomainBasedSameAsRetrieverManager.java:70)
	at org.aksw.gerbil.semantic.sameas.impl.DomainBasedSameAsRetrieverManager.retrieveSameURIs(DomainBasedSameAsRetrieverManager.java:58)
	at org.aksw.gerbil.semantic.sameas.impl.UriFilteringSameAsRetrieverDecorator.retrieveSameURIs(UriFilteringSameAsRetrieverDecorator.java:56)
	at org.aksw.gerbil.semantic.sameas.impl.CrawlingSameAsRetrieverDecorator.addSameURIs(CrawlingSameAsRetrieverDecorator.java:73)
	at org.aksw.gerbil.semantic.sameas.impl.CrawlingSameAsRetrieverDecorator.retrieveSameURIs(CrawlingSameAsRetrieverDecorator.java:52)
	at org.aksw.gerbil.semantic.sameas.impl.cache.FileBasedCachingSameAsRetriever.requestUri(FileBasedCachingSameAsRetriever.java:147)
	at org.aksw.gerbil.semantic.sameas.impl.cache.FileBasedCachingSameAsRetriever.retrieveSameURIs(FileBasedCachingSameAsRetriever.java:135)
	at org.aksw.gerbil.semantic.sameas.impl.AbstractSameAsRetrieverDecorator.addSameURIs(AbstractSameAsRetrieverDecorator.java:43)
	at org.aksw.gerbil.semantic.sameas.SameAsRetrieverUtils.addSameURIsToMarkings(SameAsRetrieverUtils.java:31)
	at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getPreparedDataset(AbstractDatasetConfiguration.java:75)
	at org.aksw.gerbil.dataset.SingletonDatasetConfigImpl.getPreparedDataset(SingletonDatasetConfigImpl.java:50)
	at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getDataset(AbstractDatasetConfiguration.java:50)
	at org.aksw.gerbil.execute.ExperimentTask.run(ExperimentTask.java:104)
	at org.aksw.simba.topicmodeling.concurrent.workers.WorkerImpl.run(WorkerImpl.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.aksw.gerbil.http.AbstractHttpRequestEmitter.sendRequest(AbstractHttpRequestEmitter.java:151)
	... 20 more
```

**Comment by RicardoUsbeck** [comment]
> Sorry, I am not very familiar with gerbil, I don’t know how to restart the web service. All gerbil services have been closed.
> <img alt="Screen Shot 2020-12-01 at 10 30 04 AM" width="1432" src="https://user-images.githubusercontent.com/29746659/100689831-37edc980-33c0-11eb-87f4-a3aed3cab5c9.png">

If that is from the web interface at our servers, there are many concurrent users and there is no way how you can stop the other users' experiments.

**Comment by MichaelRoeder** [comment]
It seems like I misunderstood your request. I assumed that you used GERBIL locally while the screenshot seems to come from our online platform. As @RicardoUsbeck already pointed out, it is not possible to stop experiments—regardless who started them. In between, we had to restart our GERBIL service and all experiments that were still running have been stopped. So feel free to start a new experiment.

The exceptions that you see in the console come from the same as retrieval and can be ignored.

I think it would be the best if you could briefly try to explain what you want to achieve. Based on that, it is much easier to help you.

**Comment by BeerTai** [comment]
Thank you for your reply. I want to reproduce the results of REL (https://github.com/informagi/REL/blob/master/tutorials/03_Evaluate_Gerbil.md) on the Gerbil platform. The code and data are on the remote server, but when I click Add another annotator, I always get error 
![image](https://user-images.githubusercontent.com/29746659/100949564-84aedd00-3545-11eb-88ea-130dd1b52f37.png)

**Comment by MichaelRoeder** [comment]
If I am not mistaken `172.18.*.*` are [private IP addresses](https://en.wikipedia.org/wiki/IP_address#Private_addresses). So our server can not reach your application. If you don't have a public IP Address available, you will have to run GERBIL locally.

**Comment by BeerTai** [comment]
Thanks for your reply! It helps me a lot. Running GERBIL locally, is it similar to [https://github.com/dalab/end2end_neural_el#gerbil-evaluation](url)？. Are there other ways? I'm not very familiar with Java.

**Comment by RicardoUsbeck** [comment]
Yes this seems to be a very good manual on how to do it
