### ISSUE TITLE
[QA] HTTP 400 seems to end experiment

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/gerbil#383]
## Description
It seems like an HTTP error in Jena can stop the execution of an experiment.

```
2021-03-12 11:19:33,481 [pool-39-thread-1] ERROR [org.aksw.gerbil.execute.ExperimentTask] - <Got an error while running the task. Storing the error code in the db...>
org.aksw.gerbil.exceptions.GerbilException: HttpException: 400 HTTP 400 error making the query: Bad Request
        at org.aksw.gerbil.execute.ExperimentTask.runExperiment(ExperimentTask.java:599) ~[classes/:?]
        at org.aksw.gerbil.execute.ExperimentTask.run(ExperimentTask.java:167) [classes/:?]
        at org.aksw.simba.topicmodeling.concurrent.workers.WorkerImpl.run(WorkerImpl.java:44) [topicmodeling.concurrent-0.0.2-20160315.131022-1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: org.apache.jena.sparql.engine.http.QueryExceptionHTTP: HTTP 400 error making the query: Bad Request
        at org.apache.jena.sparql.engine.http.HttpQuery.rewrap(HttpQuery.java:371) ~[jena-arq-3.6.0.jar:3.6.0]
        at org.apache.jena.sparql.engine.http.HttpQuery.execPost(HttpQuery.java:359) ~[jena-arq-3.6.0.jar:3.6.0]
        at org.apache.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:287) ~[jena-arq-3.6.0.jar:3.6.0]
        at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execResultSetInner(QueryEngineHTTP.java:348) ~[jena-arq-3.6.0.jar:3.6.0]
        at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:340) ~[jena-arq-3.6.0.jar:3.6.0]
        at org.aksw.gerbil.dataset.converter.impl.SPARQLBasedLiteral2Resource.getResourcesForLiteral(SPARQLBasedLiteral2Resource.java:51) ~[classes/:?]
        at org.aksw.gerbil.dataset.converter.Literal2ResourceManager.getResourcesForLiteral(Literal2ResourceManager.java:35) ~[classes/:?]
        at org.aksw.gerbil.dataset.converter.Literal2ResourceManager.getResourcesForLiteral(Literal2ResourceManager.java:24) ~[classes/:?]
        at org.aksw.gerbil.matching.impl.QAMatchingsCounter.forceAnnotationCreation(QAMatchingsCounter.java:171) ~[classes/:?]
        at org.aksw.gerbil.matching.impl.QAMatchingsCounter.countMatchings(QAMatchingsCounter.java:143) ~[classes/:?]
        at org.aksw.gerbil.evaluate.impl.FMeasureCalculator.generateMatchingCounts(FMeasureCalculator.java:89) ~[classes/:?]
        at org.aksw.gerbil.evaluate.impl.FMeasureCalculator.evaluate(FMeasureCalculator.java:70) ~[classes/:?]
        at org.aksw.gerbil.evaluate.AbstractTypeTransformingEvaluatorDecorator.evaluate(AbstractTypeTransformingEvaluatorDecorator.java:41) ~[classes/:?]
        at org.aksw.gerbil.execute.ExperimentTask.evaluate(ExperimentTask.java:618) ~[classes/:?]
        at org.aksw.gerbil.execute.ExperimentTask.runExperiment(ExperimentTask.java:593) ~[classes/:?]
        ... 5 more
```

It should be discussed whether this is an expected behavior or whether the experiment should go on.

**Comment by TortugaAttack** [comment]
Fixed by expanding the try/catch.
before: aborts the experiment at any error in the SPARQL Literal 2 resource converter 
now: catches a wrong request and returns the literal instead of a retrieved resource.
