### ISSUE TITLE
Problem getting AIDA/CoNLL results for experiments using custom annotator

### ISSUE THREAD

**Issue by hvwesten** [dice-group/gerbil#390]
Hi,

So far I've mostly been successful in getting results for my experiments on the online GERBIL platform using a custom annotator based on [REL](https://github.com/informagi/rel). The problem I ran into is that, although I started a new experiment 7 days ago to get scores on several datasets and got results on most of these datasets, I still have not received scores on the AIDA/CoNLL or the N3-RSS-500 dataset. When I ran the experiment again the website mentioned that 
> Experiments could take a while
> There are 17 other tasks pending before your latest task on 12 Worker(s)

Now, 7 days later, I am not sure on what to do next. When running the same experiment on just these datasets, it tells me that there are *21* other tasks pending. Any ideas?

**Comment by MichaelRoeder** [comment]
Thanks for using GERBIL. We are sorry that you encountered problems.
Can you please provide us the links to the experiments you started? From what I gathered, there are no experiments running at the moment. :confused:

**Comment by hvwesten** [comment]
Of course! This is the link for the experiment I started this morning. http://gerbil.aksw.org/gerbil/experiment?id=202104280000

**Comment by MichaelRoeder** [comment]
The service run out of memory. The cause for that is not clear until now.

Output on cmd line:
```
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
[Fatal Error] :1:50: White spaces are required between publicId and systemId.
Apr 17, 2021 2:05:11 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
Apr 17, 2021 7:33:06 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
Apr 17, 2021 7:33:07 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
Apr 19, 2021 6:51:19 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
Apr 19, 2021 6:51:22 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
Apr 21, 2021 9:29:17 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/gerbil] threw exception [Request processing failed; nested exception is org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [SELECT rn.name, 'DOUBLE' AS Type, dr.resvalue FROM ExperimentTasks_DoubleResults dr, ResultNames rn WHERE dr.resultId = rn.id and dr.taskId = ?]; java.lang.OutOfMemoryError: GC overhead limit exceeded; nested exception is java.sql.SQLException: java.lang.OutOfMemoryError: GC overhead limit exceeded] with root cause
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception in thread "http-bio-8080-exec-76" java.lang.OutOfMemoryError: GC overhead limit exceeded
Apr 21, 2021 12:59:05 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
Apr 21, 2021 12:59:05 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
Apr 24, 2021 5:29:35 AM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
Exception in thread "http-bio-8080-exec-196" java.lang.OutOfMemoryError: GC overhead limit exceeded
```
log file: [gerbil.log](https://github.com/dice-group/gerbil/files/6391906/gerbil.log)

I see several issues:
- GERBIL does not handle experiment tasks that died correctly. It still assumes that they are running.
- Several experiments are aborted because the machine runs out of memory.
- `[Fatal Error] :1:50: White spaces are required between publicId and systemId.` I have no idea where this comes from.

I will restart the service and try to get more memory. However, this may not solve the problem (at least not in the long run) :thinking:

**Comment by MichaelRoeder** [comment]
Some positions at which the service runs out of memory (gathered from the log file above):

```
2021-04-09 20:22:50,143 [pool-1-thread-9] ERROR [org.aksw.simba.topicmodeling.concurrent.reporter.LogReporter] - <Task=ExperimentTask("eTConfig("AIDA","AIDA/CoNLL-Test A","A2KB","STRONG_ANNOTATION_MATCH")")	state=TERMINATED	with exception: java.lang.OutOfMemoryError: Java heap space
	at java.io.ObjectOutputStream$HandleTable.growEntries(ObjectOutputStream.java:2351)
	at java.io.ObjectOutputStream$HandleTable.assign(ObjectOutputStream.java:2276)
	at java.io.ObjectOutputStream.writeString(ObjectOutputStream.java:1302)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1172)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.aksw.gerbil.dataset.check.impl.FileBasedCachingEntityCheckerManager.performCacheStorage(FileBasedCachingEntityCheckerManager.java:235)
	at org.aksw.gerbil.dataset.check.impl.FileBasedCachingEntityCheckerManager.checkUri(FileBasedCachingEntityCheckerManager.java:180)
```
```
2021-04-10 00:20:15,795 [pool-1-thread-10] ERROR [org.aksw.simba.topicmodeling.concurrent.reporter.LogReporter] - <Task=ExperimentTask("eTConfig("AIDA","AIDA/CoNLL-Test B","A2KB","STRONG_ANNOTATION_MATCH")")	state=TERMINATED	progress=100.0% of dataset	with exception: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap$KeySet.iterator(HashMap.java:917)
	at java.util.HashSet.iterator(HashSet.java:173)
	at org.aksw.gerbil.transfer.nif.MeaningEqualityChecker.overlaps(MeaningEqualityChecker.java:42)
	at org.aksw.gerbil.matching.impl.AbstractMeaningMatchingsSearcher.findMatchings(AbstractMeaningMatchingsSearcher.java:59)
	at org.aksw.gerbil.matching.impl.AbstractMeaningMatchingsSearcher.findMatchings(AbstractMeaningMatchingsSearcher.java:37)
	at org.aksw.gerbil.matching.impl.CompoundMatchingsSearcher.findMatchings(CompoundMatchingsSearcher.java:40)
	at org.aksw.gerbil.matching.impl.MatchingsCounterImpl.countMatchings(MatchingsCounterImpl.java:48)
	at org.aksw.gerbil.matching.scored.ScoredMatchingsCounterImpl.countMatchings(ScoredMatchingsCounterImpl.java:74)
	at org.aksw.gerbil.evaluate.impl.ConfidenceBasedFMeasureCalculator.generateMatchingCounts(ConfidenceBasedFMeasureCalculator.java:68)
```
```
2021-04-21 09:44:32,120 [pool-1-thread-2] ERROR [org.aksw.simba.topicmodeling.concurrent.reporter.LogReporter] - <Task=ExperimentTask("eTConfig("REL-Clueweb (NIF WS)","N3-RSS-500","D2KB","STRONG_ANNOTATION_MATCH")")	state=TERMINATED	progress=72.8% of dataset	with exception: org.apache.jena.ext.com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.jena.ext.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at org.apache.jena.ext.com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at org.apache.jena.ext.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at org.apache.jena.atlas.lib.cache.CacheGuava.getOrFill(CacheGuava.java:58)
	at org.apache.jena.riot.system.IRIResolver$IRIResolverNormal.resolveSilentCache(IRIResolver.java:473)
	at org.apache.jena.riot.system.IRIResolver$IRIResolverNormal.resolveSilent(IRIResolver.java:457)
	at org.apache.jena.riot.system.ParserProfileChecker.makeIRI(ParserProfileChecker.java:63)
	at org.apache.jena.riot.system.ParserProfileChecker.resolveIRI(ParserProfileChecker.java:57)
	at org.apache.jena.riot.system.ParserProfileChecker.createURI(ParserProfileChecker.java:109)
	at org.apache.jena.riot.system.ParserProfileBase.create(ParserProfileBase.java:169)
	at org.apache.jena.riot.system.ParserProfileBase.create(ParserProfileBase.java:152)
	at org.apache.jena.riot.lang.LangTurtleBase.tokenAsNode(LangTurtleBase.java:499)
	at org.apache.jena.riot.lang.LangTurtleBase.node(LangTurtleBase.java:341)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesNode(LangTurtleBase.java:366)
	at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:349)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:287)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:268)
	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:249)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:190)
	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:89)
	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:42)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:179)
	at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:861)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:259)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:245)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
	at org.aksw.gerbil.io.nif.impl.TurtleNIFParser.parseNIFModel(TurtleNIFParser.java:46)
	at org.aksw.gerbil.io.nif.AbstractNIFParser.parseNIF(AbstractNIFParser.java:81)
	at org.aksw.gerbil.io.nif.AbstractNIFParser.parseNIF(AbstractNIFParser.java:76)
	at org.aksw.gerbil.transfer.nif.AbstractNIFDocumentParser.getDocumentFromNIFStream(AbstractNIFDocumentParser.java:68)
```
There are 14 Exceptions but the LogReporter decided not to print the others since the exception class is always the same.

**Comment by MichaelRoeder** [comment]
@hvwesten The service is back (e.g., http://gerbil.aksw.org/gerbil/experiment?id=202104290000). Please feel free to start the failed experiments again. I would suggest to start a single experiment just to see whether the problem occurs again :wink: 

In case you end up in the same situation again (the UI tells you that the experiment is running but you are not sure whether that is really true), have a look at the debugging page http://gerbil.aksw.org/gerbil/running. If you see your experiment listed there, it is still running. In any case, we will have a closer look at the service during the next days.

**Comment by hvwesten** [comment]
It seems like my experiments are working again, thanks for your help!
