### ISSUE TITLE
Setup Error on Amazon EC2

### ISSUE THREAD

**Issue by bigheiniu** [dice-group/gerbil#417]
Hi there, 
Thanks for the brilliant work. 
I have followed the setup instructions in [wiki](https://github.com/dice-group/gerbil/wiki/How-to-setup-GERBIL) to install local GERBIL. 
However, when I run the "./start.sh" and click "add another annotator".
<img width="831" alt="image" src="https://user-images.githubusercontent.com/14136541/173177482-34d2beb9-fc45-4fc9-9318-4a59b1e329b8.png">

**The backend throws error:**

`SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/gerbil] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.setContentLengthLong(J)V] with root cause
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.setContentLengthLong(J)V
        at org.springframework.http.server.ServletServerHttpResponse.writeHeaders(ServletServerHttpResponse.java:130)
        at org.springframework.http.server.ServletServerHttpResponse.getBody(ServletServerHttpResponse.java:96)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:137)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:129)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:45)
        at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
        at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:555)
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

And I cannot choose any datasets to evaluate my model. 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/14136541/173177567-b3386eea-f9ba-481c-8621-2dd0c7494ac7.png">

Is there any suggestions for solving this problem? 
Best,
Yichuan

**Comment by MichaelRoeder** [comment]
Hi Yichuan,

thanks for using GERBIL. I edited your post a little bit to format the stack trace in a better way.

To me, it looks like the Spring version that we use at the moment is not compatible with your Java version. From the stack trace, you can see that the `ServletServerHttpResponse` class of the Spring framework tries to use the method `javax.servlet.http.HttpServletResponse.setContentLengthLong(J)`. The package name is an indication that the class is offered by the Java framework. However, it seems like the Spring framework tries to call a method which does not exist in the Java version you use.

Can you please check the Java version?
